### ISSUE TITLE
Explore Semantic UI

### ISSUE THREAD

**Issue by ToriRae324** [ToriRae324/project3#2]
The usage of Semantic-UI with React is much simpler than what was initially thought and the site could be built with just the landing page component, user form, login/create login, and 1 api carousel component that we just pass information to in different ways.

**Comment by BlaiseAK** [comment]
import React from 'react';
import {Grid} from 'semantic-ui-react';

const ContainerFluid = () => (
    <Grid>
    <Grid.Row>
      <Grid.Column className="title" width={6}>
      <h1>Name</h1>
      </Grid.Column>
    </Grid.Row>
  </Grid>
);

export default ContainerFluid;
